post = {
  section_id: 2,
  title: 'Superar el miedo a hablar en público',
  body: <<BODY
<p>Año 1993, gala de los Oscar. El joven actor Leonardo DiCaprio acude nominado&nbsp;por la película ¿A quién ama Gilbert Grape?, y en vez de sentir alegría o euforia por el&nbsp;gran reconocimiento que supone siente miedo, está aterrorizado.</p>
<p>Se ha dado cuenta de que la ceremonia es retransmitida en directo en todo el&nbsp;mundo. Si gana, tendrá que dar un discurso delante de millones de personas. Por&nbsp;desgracia, o alivio para él,&nbsp;el premio fue a parar a las manos de Tommy Lee Jones por&nbsp;El fugitivo y DiCaprio no tuvo que enfrentarse a la situación temida.&nbsp;</p>
<p>¿Por qué una persona con una profesión en la que te expones al mundo puede&nbsp;sentirse amenazado al hablar en público? Leonardo DiCaprio explicaba que cuando está&nbsp;rodando una película no hay mucha gente observándole y además puede realizar todas&nbsp;las tomas que quiera hasta que salga perfecto.&nbsp;</p>
<p>Sin embargo, cuando tiene que hablar en público, lo pasa mal porque &nbsp;piensa que&nbsp;no lo va a hacer tan bien como esperan de él y se llevarán una mala impresión. Si te&nbsp;preocupa mucho la impresión que vayas a causar en los oyentes y <strong>crees que no lo vas a&nbsp;hacer bien</strong>, te encontrarás <strong>ante una situación amenazante</strong>, y por lo tanto sufrirás lo&nbsp;que llamamos una <strong>respuesta de ansiedad</strong>.&nbsp;</p>
<p><strong>¿CÓMO SE MANIFIESTA LA ANSIEDAD AL HABLAR EN PÚBLICO?&nbsp;</strong></p>
<p><strong>Profecía autocumplida</strong>. “No lo voy a hacer bien”, “seguro que se ríen de mí”, “me&nbsp;voy a poner nervioso/a y se me va a notar”. Todos estos pensamientos son&nbsp;<strong>anticipaciones</strong> que hacemos de lo que creemos que va a ocurrir, adelantamos&nbsp;situaciones que <strong>no tienen por qué suceder</strong> y muchas veces, precisamente por pensar eso, acaban sucendiendo. No te dejes llevar por tu adivino interno, se&nbsp;equivoca casi siempre.&nbsp;</p>
<p><strong>Tu cuerpo emite señales de alerta</strong>. Las más frecuentes son palpitaciones,&nbsp;temblores, respiración agitada, sudoración, tensión muscular, rubor en las mejillas,&nbsp;sensación de ahogo y taquicardia. Tienes <strong>la sensación de que el público se está dando&nbsp;cuenta</strong> de todo, y lo habitual es que no suelen percatarse de que lo estamos pasando&nbsp;mal. A los espectadores no les parecen señales importantes, pero en eso momento a ti sí&nbsp;que te lo parecen.&nbsp;</p>
<p><strong>Acción o inacción, pero reacción</strong>. Tu repertorio de movimientos y conductas&nbsp;puede no ser coherente con la situación real. Puede ser por exceso como <strong>tocarse la&nbsp;cara</strong>, el pelo u otras partes del cuerpo, morderse las uñas, <strong>acelerar el discurso</strong>,&nbsp;<strong>moverse mucho por la sala</strong>, abandonar el lugar o la situación temidos; o por defecto, como <strong>no decir nada, quedarse quieto en el sitio, no gesticular</strong>, balbucear.&nbsp;</p>
<p>Un caso reciente es el del escritor y cantante Joaquín Sabina, que hace unos&nbsp;meses sufrió un <a href="http://www.elmundo.es/cultura/2014/12/13/548cc4acca474145748b48e8.html">ataque de pánico</a>, lo que él llamó un "Pastora Soler". Canceló el&nbsp;concierto una vez empezado. A pesar de las tablas de un artista que lleva casi cuatro&nbsp;décadas de trayectoria, explicó que le ocurrió debido a “un exceso de ganas de estar&nbsp;bien delante de mi gente de Madrid”.&nbsp;</p>
<p>Otra vez se repite el mismo patrón, como con Leonardo DiCaprio: <strong>personas&nbsp;expectantes, la creencia de que es necesario hacerlo muy bien y anticipar de forma&nbsp;errónea que no se está a la altura.&nbsp;</strong></p>
<p>Si te has sentido excesivamente nervioso al exponer un trabajo, por recoger un&nbsp;premio o explicar un tema en público, la próxima vez puedes elegir entre dos maneras&nbsp;de responder: <strong>Una agravará el problema, la otra será el comienzo de la solución.&nbsp;</strong></p>
<p><strong>1.- Perpetuar la ansiedad</strong>: Evita la situación y no des la charla. Cuando te&nbsp;encuentras ante una situación temida sientes un intenso malestar y tienes la impresión&nbsp;de que va a continuar al máximo hasta que termines de hablar. Si abandonas la&nbsp;situación, cesa el malestar y te sientes aliviado.&nbsp;</p>
<p>Pero la próxima vez que te encuentres en una situación parecida, tendrás todavía&nbsp;más miedo y te costará más conseguir tu objetivo. Pensarás que si la última vez no&nbsp;fuiste capaz, esta vez tampoco lo podrás conseguir. El problema es que <strong>al huir no has&nbsp;comprobado que el malestar se reduce de manera natural</strong>, y crees que la única&nbsp;forma de salvarte es huyendo.&nbsp;</p>
<p><strong>2.- ¡A por ellos!</strong> Exponte a la situación. Permítete sentir las sensaciones que&nbsp;tienes. Sabes que son sensaciones, no más, y comprobarás cómo, aunque estés nervioso&nbsp;al principio, la angustia va disminuyendo a medida que avanza la charla.&nbsp;</p>
<p>La ansiedad es un proceso que sigue un patrón característico: <strong>ante la situación&nbsp;temida se dispara el malestar creciendo rápidamente en pocos minutos, y tras&nbsp;alcanzar el pico máximo va disminuyendo lentamente</strong>. Nuestro cuerpo no está&nbsp;preparado para mantener un nivel de ansiedad tan elevado durante mucho tiempo, si&nbsp;dejas que la curva natural de la ansiedad siga su curso, verás que esta disminuirá&nbsp;progresivamente tras los 10-15 primeros minutos.&nbsp;</p>
<p><strong>¿QUÉ SE PUEDE HACER PARA COMBATIREL MIEDO?</strong></p>
<p>1. Trata de <strong>no adelantar situaciones</strong> que no sabes si van a ocurrir. Mentalízate de&nbsp;que aunque no hables tan bien como tú quisieras, los oyentes pueden quedarse&nbsp;satisfechos igualmente. El mundo no se acaba porque no hagas la mejor&nbsp;interpretación de tu vida.</p>
<p>2. Para reducir el miedo lo mejor es <strong>exponerte a la situación</strong>, es decir, la próxima&nbsp;vez que tengas que hablar en público ¡hazlo!, comprobarás que no resulta tan&nbsp;angustioso y que el nerviosismo del principio se va pasando poco a poco. Hasta&nbsp;los artistas más experimentados se agitan un poco antes de salir al escenario.</p>
<p>Unas pequeñas <strong>claves para empezar</strong>:</p>
<p>-<strong>Paso a paso</strong>: empieza hablando delante de familia y amigos, cuando estés más confiado, en reuniones de pocas personas, hasta llegar a grandes auditorios. El límite lo pones tú.</p>
<p>-<strong>Permanece en el lugar</strong>: cuanto más tiempo estés hablando o exponiéndote al miedo, mejor. Es importante que le muestres a tu cerebro que la situación no es realmente amenazante. La ansiedad llegará a su máximo nivel pero progresivamente, irá disminuyendo. Cuando hayas notado que la ansiedad se ha reducido mucho o incluso ha desaparecido habrás ganado al miedo y la próxima vez te será más fácil conseguir tu objetivo.</p>
<p>-Hazte consciente mientras hablas de <strong>cómo está tu cuerpo</strong>, cómo es tu respiración, cómo están tus manos, etc. Comprobarás cómo esas sensaciones desagradables van disminuyendo poco a poco hasta que ya dejan de ser molestas.</p>
<p style="margin-left:72.0pt">&nbsp;</p>
<p>3.&nbsp;Para reducir las sensaciones físicas de la ansiedad puedes seguir las siguientes indicaciones:</p>
<p>-<strong>Intenta hacer que tus respiraciones sean más acompasadas</strong>, aunque al &nbsp;principio puedan ser muy rápidas, respirando de manera regular conseguirás hacer poco a poco respiraciones más lentas. Así, rebajarás tu nivel de ansiedad y afrontarás la charla más calmado.</p>
<p>-<strong>Bebe un poco de agua </strong>o toma un caramelo. De esta forma tu cuerpo sabrá que estás ante una situación normal, sin peligros a la vista, y se relajará de una manera natural.</p>
<p>-Práctica alguna <strong>técnica de relajación</strong> como <a href="http://tecnicasderespiracion.com/respiracion-diafragmatica/">respiración diafragmática</a>, yoga, <a href="http://www.psicologia-online.com/autoayuda/aprender-a-relajar/entrenamiento-en-relajacion-muscular-progresiva.html">relajación muscular progresiva</a>, <a href="http://www.psicologia-online.com/autoayuda/relaxs/autogeno.htm">relajación autógena</a>, etc. Una vez vayas dominando la relajación, te será más fácil reducir tus síntomas de ansiedad cuando vayas a hablar en público.</p>
<p>-<strong>Busca estrategias</strong> que te ayuden a comunicarte mejor. Algunas ideas que puedes poner en práctica:</p>
<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;-Prepara lo que vas a decir. Si lo escribes íntegro y subrayas las partes importantes tienes la seguridad de que en caso extremo de bloqueo podrás leerlo con facilidad.</p>
<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;-Practica en casa, puedes hacerlo delante del espejo o grabándote en vídeo. Podrás ajustar la comunicación al tiempo establecido, ver qué partes te cuestan más y en cuáles hacer preguntas a los oyentes, etc. La idea es que puedas ver qué cosas haces bien y cuales puedes mejorar.</p>
<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;-Más vale dejar a los oyentes con ganas de más que aburrirlos. Ante la duda, se breve. Decide cuáles son los puntos importantes de la charla y céntrate en ellos.</p>
<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;-Hay centenares de <a href="http://www.casadellibro.com/busqueda-generica?busqueda=hablar+en+p%C3%BAblico&amp;nivel=5&amp;auto=0&amp;maxresultados=10">libros</a>, <a href="https://www.google.es/webhp?sourceid=chrome-instant&amp;rlz=1C1SKPL_enES452ES452&amp;ion=1&amp;espv=2&amp;ie=UTF-8#q=curso+oratoria">cursos</a> y <a href="https://www.youtube.com/results?search_query=t%C3%A9cnicas+hablar+en+p%C3%BAblico">vídeos</a> que te proporcionarán las herramientas necesarias para ser un buen orador y te ayudarán a sentirte más seguro la próxima vez que tengas que hablar en público.</p>
<p>Y recuerda, <strong>la situación en sí no es peligrosa, somos nosotros los que le damos ese significado</strong>. Depende de ti enfrentarte a tu miedo y comprobar que hablar en público no resulta tan terrible.</p>
<p>Carlos Salas Merino</p>
<p>Psicólogo</p>
BODY
}
Post.find_or_create_by(post)
