default: &default
  cloudinary:
    api_key: <%= ENV['CLOUNDINARY_API_KEY'] %>
    api_secret: <%= ENV['CLOUNDINARY_API_SECRET'] %>
development:
  <<: *default
  secret_key_base: f9d5632120b46e20d835a400dc5bc7db51ed24a2d5856b028fbf49904a00387c4b5230e6846bac9dd2fd2225c812a7064cb6b7de3307852975a74bbb83d84661
production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
