address:
  street: Avenida de Badajoz
  number: 3
  postal_code: 28027
  city: Madrid
full_address: Avenida de Badajoz, 3, 28027 Madrid
phone: 918 27 33 20
mobile_phone: 664 47 60 55
email: confianzayfisioterapia@gmail.com
reservations_url: https://connect.shore.com/widget/confisio?locale=es
